# Generated by Django 4.2.28 on 2026-02-20 01:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_modified'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty')], db_index=True, default='faculty', max_length=10)),
                ('avatar_url', models.URLField(blank=True, default='', help_text="URL to the user's avatar image.")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='TimetableVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fitness', models.FloatField(default=0.0, help_text='Fitness score (0.0 to 1.0) — 1.0 is a perfect schedule.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('execution_time', models.PositiveIntegerField(default=0, help_text='Execution time in milliseconds.')),
                ('hard_violations', models.PositiveIntegerField(default=0, help_text='Count of hard constraint violations.')),
                ('soft_violations', models.PositiveIntegerField(default=0, help_text='Count of soft constraint violations.')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this version is currently loaded.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('history_data', models.JSONField(blank=True, default=dict, help_text='Full schedule data, fitness trend, and GA config.')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_versions', to='scheduling.workspace')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('size', models.PositiveIntegerField(help_text='Number of students in this group.', validators=[django.core.validators.MinValueValidator(1)])),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='scheduling.workspace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(db_index=True, max_length=150)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='Lecturer scheduling preferences for the GA engine. Example: {"preferred_timeslots": [1, 5, 9], "max_daily_hours": 4, "avoid_days": [4]}')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturers', to='scheduling.workspace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of seats.', validators=[django.core.validators.MinValueValidator(1)])),
                ('building', models.CharField(blank=True, default='', help_text='Building or campus location.', max_length=100)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='scheduling.workspace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed course description / pedagogical notes.')),
                ('duration_hours', models.PositiveIntegerField(default=1, help_text='Weekly contact hours (determines number of GA sessions).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='scheduling.lecturer')),
                ('student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='scheduling.studentgroup')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='scheduling.workspace')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('workspace', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ConstraintConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable constraint name.', max_length=150)),
                ('type', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft')], db_index=True, max_length=4)),
                ('logic_type', models.CharField(choices=[('room_conflict', 'Room Double-Booking'), ('lecturer_conflict', 'Lecturer Overlap'), ('capacity_check', 'Room Capacity Check'), ('time_preference', 'Lecturer Time Preference'), ('consecutive_classes', 'Consecutive Class Stacking'), ('building_proximity', 'Building Proximity'), ('day_spread', 'Day Spread Balance'), ('custom', 'Custom Rule')], db_index=True, help_text='The scheduling rule this constraint enforces.', max_length=30)),
                ('enabled', models.BooleanField(default=True, help_text='Toggle this constraint on/off without deleting.')),
                ('weight', models.PositiveIntegerField(default=100, help_text='Penalty weight. Hard constraints anchor at 1000; soft constraints range 20-100.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='scheduling.workspace')),
            ],
            options={
                'ordering': ['-type', 'name'],
                'unique_together': {('workspace', 'logic_type')},
            },
        ),
    ]
