# Generated by Django 4.2.28 on 2026-02-21 02:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_tasktracker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constraintconfig',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building', 'name']},
        ),
        migrations.AlterModelOptions(
            name='timetableversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='constraintconfig',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='timetableversion',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='course',
            name='requires_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='timetableversion',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableversion',
            name='generations_run',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='constraintconfig',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='constraintconfig',
            name='logic_type',
            field=models.CharField(choices=[('room_conflict', 'Room Double Booking'), ('lecturer_conflict', 'Lecturer Double Booking'), ('group_conflict', 'Group Double Booking'), ('capacity_overflow', 'Room Capacity Exceeded'), ('lecturer_preference', 'Lecturer Preference Ignored')], max_length=50),
        ),
        migrations.AlterField(
            model_name='constraintconfig',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='constraintconfig',
            name='type',
            field=models.CharField(choices=[('hard', 'Hard Constraint'), ('soft', 'Soft Constraint')], max_length=10),
        ),
        migrations.AlterField(
            model_name='constraintconfig',
            name='weight',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='constraintconfig',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='scheduling.workspace'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.IntegerField(default=1, help_text='Length of the class in hours (e.g., 1, 2, or 3).'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='scheduling.lecturer'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='scheduling.studentgroup'),
        ),
        migrations.AlterField(
            model_name='course',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='scheduling.workspace'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object for scheduling preferences (soft constraints).'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturers', to='scheduling.workspace'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(blank=True, default='Main', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='scheduling.workspace'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='scheduling.workspace'),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetableversion',
            name='execution_time',
            field=models.FloatField(help_text='Time taken in milliseconds.'),
        ),
        migrations.AlterField(
            model_name='timetableversion',
            name='fitness',
            field=models.FloatField(help_text='Final fitness score of this solution.'),
        ),
        migrations.AlterField(
            model_name='timetableversion',
            name='hard_violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timetableversion',
            name='history_data',
            field=models.JSONField(default=dict, help_text='Serialized timetable structure and analytics.'),
        ),
        migrations.AlterField(
            model_name='timetableversion',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only one version is active for the public view.'),
        ),
        migrations.AlterField(
            model_name='timetableversion',
            name='soft_violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
