# Generated by Django 4.2.28 on 2026-02-21 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_constraintconfig_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='scheduling.lecturer'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='scheduling.studentgroup'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timetableversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timetableversion',
            name='execution_time',
            field=models.FloatField(default=0.0, help_text='Time taken in milliseconds.'),
        ),
        migrations.AlterField(
            model_name='timetableversion',
            name='fitness',
            field=models.FloatField(default=0.0, help_text='Final fitness score of this solution.'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
