# Generated by Django 4.2.28 on 2026-02-22 00:56

from django.db import migrations, models
import scheduling.validators_schemas


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_course_lecturer_alter_course_student_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object for scheduling preferences (soft constraints).', validators=[scheduling.validators_schemas.validate_lecturer_preferences]),
        ),
        migrations.AddIndex(
            model_name='tasktracker',
            index=models.Index(fields=['workspace', 'status'], name='scheduling__workspa_a2fdc6_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktracker',
            index=models.Index(fields=['-created_at'], name='scheduling__created_6fff71_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableversion',
            index=models.Index(fields=['workspace', 'is_active'], name='scheduling__workspa_88d7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableversion',
            index=models.Index(fields=['-created_at'], name='scheduling__created_90b34c_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', '-last_modified'], name='scheduling__owner_i_c909cf_idx'),
        ),
    ]
