# Generated by Django 4.2.28 on 2026-02-22 09:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0005_alter_lecturer_preferences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('head', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='scheduling.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(help_text='University student ID number', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='scheduling.department')),
                ('student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='scheduling.studentgroup')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='scheduling.workspace')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RoomUtilization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slots_used', models.IntegerField(default=0, help_text='Number of 1-hour slots room is scheduled')),
                ('total_slots', models.IntegerField(default=40, help_text='Total available slots per week (5 days × 8 hours)')),
                ('avg_capacity_used', models.FloatField(default=0.0, help_text='Average % of room capacity utilized', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('peak_hours', models.JSONField(default=list, help_text='List of timeslot IDs with highest usage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilization_records', to='scheduling.room')),
                ('timetable_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_utilizations', to='scheduling.timetableversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportedConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conflict_type', models.CharField(choices=[('room_change', 'Room Change Request'), ('time_conflict', 'Time Conflict'), ('capacity_issue', 'Capacity Issue'), ('venue_unsuitable', 'Venue Unsuitable'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('suggested_resolution', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='reported', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_reported', to='scheduling.course')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_conflicts', to=settings.AUTH_USER_MODEL)),
                ('timetable_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_conflicts', to='scheduling.timetableversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LecturerScheduleSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_hours', models.IntegerField(default=0, help_text='Total teaching hours assigned')),
                ('course_count', models.IntegerField(default=0, help_text='Number of distinct courses')),
                ('session_count', models.IntegerField(default=0, help_text='Total teaching sessions')),
                ('total_student_capacity', models.IntegerField(default=0, help_text='Sum of all student groups across sessions')),
                ('assigned_venues', models.JSONField(default=dict, help_text='Dict mapping room_id → [timeslot_ids] for quick lookup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_snapshots', to='scheduling.lecturer')),
                ('timetable_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_snapshots', to='scheduling.timetableversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='active', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='scheduling.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='scheduling.student')),
            ],
            options={
                'ordering': ['-enrolled_date'],
                'indexes': [models.Index(fields=['student', 'status'], name='scheduling__student_f6e245_idx'), models.Index(fields=['course'], name='scheduling__course__a99f16_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['workspace', 'student_group'], name='scheduling__workspa_7ed68a_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='scheduling__student_e2dad4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('workspace', 'student_id')},
        ),
        migrations.AddIndex(
            model_name='roomutilization',
            index=models.Index(fields=['timetable_version'], name='scheduling__timetab_21f09c_idx'),
        ),
        migrations.AddIndex(
            model_name='roomutilization',
            index=models.Index(fields=['room'], name='scheduling__room_id_6e8506_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomutilization',
            unique_together={('timetable_version', 'room')},
        ),
        migrations.AddIndex(
            model_name='reportedconflict',
            index=models.Index(fields=['status', '-created_at'], name='scheduling__status_34a5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='reportedconflict',
            index=models.Index(fields=['reported_by'], name='scheduling__reporte_8e04ff_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturerschedulesnapshot',
            index=models.Index(fields=['lecturer'], name='scheduling__lecture_a688d9_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturerschedulesnapshot',
            index=models.Index(fields=['timetable_version'], name='scheduling__timetab_779024_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lecturerschedulesnapshot',
            unique_together={('timetable_version', 'lecturer')},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['workspace'], name='scheduling__workspa_985452_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('workspace', 'name')},
        ),
    ]
