# Generated by Django 4.2.28 on 2026-02-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_department_student_roomutilization_reportedconflict_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
