# Generated by Django 4.2.28 on 2026-03-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_remove_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='user_profile',
            field=models.ForeignKey(blank=True, help_text='Link to the user account (for staff login).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_profiles', to='scheduling.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LECTURER', 'Lecturer')], default='ADMIN', help_text='ADMIN = full access, LECTURER = limited access.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff_id',
            field=models.CharField(blank=True, help_text='Unique staff identifier for lecturer login.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='scheduling.lecturer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
