# Generated by Django 4.2.28 on 2026-03-24 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0008_lecturer_user_profile_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this course belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='scheduling.department'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='department_obj',
            field=models.ForeignKey(blank=True, help_text='Linked department (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='scheduling.department'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LECTURER', 'Lecturer'), ('OFFICER', 'Timetable Officer')], default='ADMIN', help_text='ADMIN = full access, LECTURER = limited access.', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Human-readable description of the action.', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='scheduling.workspace')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='scheduling__timesta_d68b63_idx')],
            },
        ),
    ]
